# Copyright (c) 2017-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2017-present Sven Greb <code@svengreb.de>

# Project:    Nord Alacritty
# Version:    0.1.0
# Repository: https://github.com/arcticicestudio/nord-alacritty
# License:    MIT
# References:
#   https://github.com/jwilm/alacritty

font:
  normal:
    family: Cascadia Code
    style: Regular

  bold:
    family: Cascadia Code
    style: Bold

  italic:
    family: Cascadia Code
    style: Italic

  size: 10.5

colors:
  primary:
    background: '0x282828'
    foreground: '0xFBF1C7'
  cursor:
    text: '0x282828'
    cursor: '0xFBF1C7'
  normal:
    black: '0x282828'
    red: '0x9D0006'
    green: '0x79740E'
    yellow: '0xB57614'
    blue: '0x076678'
    magenta: '0x8F3F71'
    cyan: '0x427B58'
    white: '0xFBF1C7'
  bright:
    black: '0x32302F'
    red: '0xFB4934'
    green: '0xB8BB26'
    yellow: '0xFABD2F'
    blue: '0x83A598'
    magenta: '0xD3869B'
    cyan: '0x8EC07C'
    white: '0xFBF1C7'

# background_opacity: 0.925
