# vim: fdm=marker foldmarker=#{,#}
# Configuration docs at: https://dystroy.org/broot

# Default command-line flags
default_flags = ""

# Verbs and shortcuts #{

[[verbs]]
invocation = "edit"
key = "enter"
shortcut = "e"
execution = "$EDITOR {file}"

[[verbs]]
invocation = "echo"
execution = "echo {file}"

[[verbs]]
key = "ctrl-c"
execution = ":quit"

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
execution = "git diff {file}"

[[verbs]]
name = "view"
invocation = "view"
execution = "$PAGER {file}"

[[verbs]]
key = "ctrl-j"
execution = ":line_down"

[[verbs]]
key = "ctrl-k"
execution = ":line_up"

[[verbs]]
key = "ctrl-d"
execution = ":page_down"

[[verbs]]
key = "ctrl-u"
execution = ":page_up"

[[verbs]]
key = "ctrl-g"
execution = ":toggle_git_status"

#}
# Skin #{

[skin]
default = "white none"
tree = "ansi(8) none"
file = "white none"
directory = "blue none bold"
exe = "green none"
link = "blue none"
pruning = "rgb(89, 73, 101) none italic"
selected_line = "ansi(0) ansi(8)"
char_match = "yellow none"
file_error = "red none"
flag_label = "gray(16) none"
flag_value = "rgb(255, 152, 0) none bold"
input = "white none"
status_error = "red gray(2)"
status_job = "ansi(220) gray(5)"
status_normal = "gray(20) ansi(0)"
status_italic = "rgb(255, 152, 0) none"
status_bold = "rgb(255, 152, 0) none bold"
status_code = "ansi(229) gray(5)"
status_ellipsis = "gray(19) gray(1)"
scrollbar_track = "rgb(80, 50, 0) none"
scrollbar_thumb = "rgb(255, 187, 0) none"
help_paragraph = "gray(20) none"
help_bold = "rgb(255, 187, 0) none bold"
help_italic = "blue rgb(30, 30, 40) italic"
help_code = "gray(21) gray(3)"
help_headers = "rgb(255, 187, 0) none"

# Old:
# [skin]
# default = "white none"
# tree = "ansi(8) none"
# file = "white none"
# directory = "blue none bold"
# exe = "green none"
# link = "blue none"
# pruning = "rgb(89, 73, 101) none italic"
# perm__ = "gray(5) none"
# perm_r = "ansi(94) none"
# perm_w = "ansi(132) none"
# perm_x = "ansi(65) none"
# owner = "gray(12) none"
# group = "gray(12) none"
# selected_line = "ansi(0) ansi(3)"
# char_match = "yellow none"
# file_error = "red none"
# flag_label = "gray(16) none"
# flag_value = "rgb(255, 152, 0) none bold"
# input = "white none"
# status_error = "red gray(2)"
# status_job = "ansi(220) gray(5)"
# status_normal = "gray(20) ansi(0)"
# status_italic = "rgb(255, 152, 0) none"
# status_bold = "rgb(255, 152, 0) none bold"
# status_code = "ansi(229) gray(5)"
# status_ellipsis = "gray(19) gray(1)"
# scrollbar_track = "rgb(80, 50, 0) none"
# scrollbar_thumb = "rgb(255, 187, 0) none"
# help_paragraph = "gray(20) none"
# help_bold = "rgb(255, 187, 0) none bold"
# help_italic = "blue rgb(30, 30, 40) italic"
# help_code = "gray(21) gray(3)"
# help_headers = "rgb(255, 187, 0) none"

#}
